import { DocumentTemplate, SubscriptionPlan } from './types';

export const APP_NAME = "Kırbaş Doküman";

export const PLANS = [
  {
    id: SubscriptionPlan.MONTHLY,
    name: "Aylık Paket",
    price: "499 TL",
    period: "/ay",
    features: ["Aylık 30 Doküman", "PDF Çıktısı", "Temel Şablonlar", "E-posta Destek"],
    limit: 30,
  },
  {
    id: SubscriptionPlan.YEARLY,
    name: "Yıllık Pro",
    price: "4.999 TL",
    period: "/yıl",
    features: ["Sınırsız Doküman", "Tüm Premium Şablonlar", "Öncelikli Destek", "Fatura Entegrasyonu"],
    limit: 'UNLIMITED',
    popular: true,
  }
];

// 25-35 Document templates simulation
export const MOCK_TEMPLATES: DocumentTemplate[] = [
{ id: '(RES, GES, HES, Termik)Yüksek Gerilim İşletme Sorumluluğu Atama Yazısıı', title: '(RES, GES, HES, Termik)Yüksek Gerilim İşletme Sorumluluğu Atama Yazısıı', category: 'Dökümanlar', fileUrl: '/templates/(RES, GES, HES, Termik)Yüksek Gerilim İşletme Sorumluluğu Atama Yazısıı.docx', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Acil_Durum_Ekip_Atama', title: 'Acil Durum Ekip Atama', category: 'Dökümanlar', fileUrl: '/templates/Acil_Durum_Ekip_Atama.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'ekipBaskani','label':'Ekip Başkanı','type':'text'},{'key':'ekipUyeleri','label':'Ekip Üyeleri','type':'textarea'}] },
{ id: 'Acil_Durum_Eylem_Plani_Sablon', title: 'Acil Durum Eylem Plani Sablon', category: 'Dökümanlar', fileUrl: '/templates/Acil_Durum_Eylem_Plani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Apron_Guvenligi_Talimati_Sablon', title: 'Apron Guvenligi Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Apron_Guvenligi_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Calisan_Temsilcisi_Atama_Sablon', title: 'Calisan Temsilcisi Atama Sablon', category: 'Dökümanlar', fileUrl: '/templates/Calisan_Temsilcisi_Atama_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'temsilciAdi','label':'Çalışan Temsilcisi Adı','type':'text'},{'key':'temsilciGorevi','label':'Görevi','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Destek_Elemani_Atama_Sablon', title: 'Destek Elemani Atama Sablon', category: 'Dökümanlar', fileUrl: '/templates/Destek_Elemani_Atama_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'elemanAdi','label':'Destek Elemanı Adı','type':'text'},{'key':'destekKonusu','label':'Destek Konusu','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'EKAT_Yetki_Belgesi_Takip_Cizelgesi_Sablonu', title: 'EKAT Yetki Belgesi Takip Cizelgesi Sablonu', category: 'Dökümanlar', fileUrl: '/templates/EKAT_Yetki_Belgesi_Takip_Cizelgesi_Sablonu.docx', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Hijyen_Sanitasyon_Talimati_Sablon', title: 'Hijyen Sanitasyon Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Hijyen_Sanitasyon_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'ISG_Kurul_Tutanagi_Sablon', title: 'ISG Kurul Tutanagi Sablon', category: 'Dökümanlar', fileUrl: '/templates/ISG_Kurul_Tutanagi_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'toplantiNo','label':'Toplantı No','type':'text'},{'key':'toplantiTarihi','label':'Toplantı Tarihi','type':'date'},{'key':'alinanKararlar','label':'Alınan Kararlar','type':'textarea'}] },
{ id: 'Isyeri_Hijyen_Sanitasyon_Talimati_Sablon', title: 'Isyeri Hijyen Sanitasyon Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Isyeri_Hijyen_Sanitasyon_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Kaza_RamakKala_Bildirim_Detayli_Sablon', title: 'Kaza RamakKala Bildirim Detayli Sablon', category: 'Dökümanlar', fileUrl: '/templates/Kaza_RamakKala_Bildirim_Detayli_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'olayTarihi','label':'Olay Tarihi','type':'date'},{'key':'olayYeri','label':'Olay Yeri','type':'text'},{'key':'olayAciklamasi','label':'Olay Açıklaması','type':'textarea'}] },
{ id: 'Lashing_Talimati_Sablon', title: 'Lashing Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Lashing_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Liman_Operasyon_Guvenlik_Plani_Sablon', title: 'Liman Operasyon Guvenlik Plani Sablon', category: 'Dökümanlar', fileUrl: '/templates/Liman_Operasyon_Guvenlik_Plani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'LOTO_Formu_Sablon', title: 'LOTO Formu Sablon', category: 'Dökümanlar', fileUrl: '/templates/LOTO_Formu_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Maden_PKD_Sablon', title: 'Maden PKD Sablon', category: 'Dökümanlar', fileUrl: '/templates/Maden_PKD_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Orman_Kesim_Proseduru_Sablon', title: 'Orman Kesim Proseduru Sablon', category: 'Dökümanlar', fileUrl: '/templates/Orman_Kesim_Proseduru_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Personel_ISG_Ihtar_Detayli_Sablon', title: 'Personel ISG Ihtar Detayli Sablon', category: 'Dökümanlar', fileUrl: '/templates/Personel_ISG_Ihtar_Detayli_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'personelAdi','label':'Personel Adı','type':'text'},{'key':'ihtarNedeni','label':'İhtar Nedeni','type':'textarea'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Pestisit_Talimati_Sablon', title: 'Pestisit Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Pestisit_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'PKD_Sablon', title: 'PKD Sablon', category: 'Dökümanlar', fileUrl: '/templates/PKD_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'dokumanNo','label':'Doküman No','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'SERTİFİKA', title: 'SERTİFİKA', category: 'Dökümanlar', fileUrl: '/templates/SERTİFİKA.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Sicak_Metal_Transfer_Talimati_Sablon', title: 'Sicak Metal Transfer Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Sicak_Metal_Transfer_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Soguk_Oda_Talimati_Sablon', title: 'Soguk Oda Talimati Sablon', category: 'Dökümanlar', fileUrl: '/templates/Soguk_Oda_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Yangindan_Korunma_Dokumani_Sablon', title: 'Yangindan Korunma Dokumani Sablon', category: 'Dökümanlar', fileUrl: '/templates/Yangindan_Korunma_Dokumani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adı','type':'text','required':true},{'key':'hazirlayan','label':'Hazırlayan','type':'text'},{'key':'binaSorumlusu','label':'Bina Sorumlusu','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] }
];