import { DocumentTemplate, SubscriptionPlan } from './types';

export const APP_NAME = "Kýrbaþ Doküman";

export const PLANS = [
  {
    id: SubscriptionPlan.MONTHLY,
    name: "Aylýk Paket",
    price: "499 TL",
    period: "/ay",
    features: ["Aylýk 30 Doküman", "PDF Çýktýsý", "Temel Þablonlar", "E-posta Destek"],
    limit: 30,
  },
  {
    id: SubscriptionPlan.YEARLY,
    name: "Yýllýk Pro",
    price: "4.999 TL",
    period: "/yýl",
    features: ["Sýnýrsýz Doküman", "Tüm Premium Þablonlar", "Öncelikli Destek", "Fatura Entegrasyonu"],
    limit: 'UNLIMITED',
    popular: true,
  }
];

// 25-35 Document templates simulation
export const MOCK_TEMPLATES: DocumentTemplate[] = [
{ id: '(RES, GES, HES, Termik)Yüksek Gerilim Ýþletme Sorumluluðu Atama Yazýsýý', title: '(RES, GES, HES, Termik)Yüksek Gerilim Ýþletme Sorumluluðu Atama Yazýsýý', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/(RES, GES, HES, Termik)Yüksek Gerilim Ýþletme Sorumluluðu Atama Yazýsýý.docx', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Acil_Durum_Ekip_Atama', title: 'Acil Durum Ekip Atama', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Acil_Durum_Ekip_Atama.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'ekipBaskani','label':'Ekip Baþkaný','type':'text'},{'key':'ekipUyeleri','label':'Ekip Üyeleri','type':'textarea'}] },
{ id: 'Acil_Durum_Eylem_Plani_Sablon', title: 'Acil Durum Eylem Plani Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Acil_Durum_Eylem_Plani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Apron_Guvenligi_Talimati_Sablon', title: 'Apron Guvenligi Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Apron_Guvenligi_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Calisan_Temsilcisi_Atama_Sablon', title: 'Calisan Temsilcisi Atama Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Calisan_Temsilcisi_Atama_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'temsilciAdi','label':'Çalýþan Temsilcisi Adý','type':'text'},{'key':'temsilciGorevi','label':'Görevi','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Destek_Elemani_Atama_Sablon', title: 'Destek Elemani Atama Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Destek_Elemani_Atama_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'elemanAdi','label':'Destek Elemaný Adý','type':'text'},{'key':'destekKonusu','label':'Destek Konusu','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'EKAT_Yetki_Belgesi_Takip_Cizelgesi_Sablonu', title: 'EKAT Yetki Belgesi Takip Cizelgesi Sablonu', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/EKAT_Yetki_Belgesi_Takip_Cizelgesi_Sablonu.docx', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Hijyen_Sanitasyon_Talimati_Sablon', title: 'Hijyen Sanitasyon Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Hijyen_Sanitasyon_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'ISG_Kurul_Tutanagi_Sablon', title: 'ISG Kurul Tutanagi Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/ISG_Kurul_Tutanagi_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'toplantiNo','label':'Toplantý No','type':'text'},{'key':'toplantiTarihi','label':'Toplantý Tarihi','type':'date'},{'key':'alinanKararlar','label':'Alýnan Kararlar','type':'textarea'}] },
{ id: 'Isyeri_Hijyen_Sanitasyon_Talimati_Sablon', title: 'Isyeri Hijyen Sanitasyon Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Isyeri_Hijyen_Sanitasyon_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Kaza_RamakKala_Bildirim_Detayli_Sablon', title: 'Kaza RamakKala Bildirim Detayli Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Kaza_RamakKala_Bildirim_Detayli_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'olayTarihi','label':'Olay Tarihi','type':'date'},{'key':'olayYeri','label':'Olay Yeri','type':'text'},{'key':'olayAciklamasi','label':'Olay Açýklamasý','type':'textarea'}] },
{ id: 'Lashing_Talimati_Sablon', title: 'Lashing Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Lashing_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Liman_Operasyon_Guvenlik_Plani_Sablon', title: 'Liman Operasyon Guvenlik Plani Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Liman_Operasyon_Guvenlik_Plani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'LOTO_Formu_Sablon', title: 'LOTO Formu Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/LOTO_Formu_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Maden_PKD_Sablon', title: 'Maden PKD Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Maden_PKD_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Orman_Kesim_Proseduru_Sablon', title: 'Orman Kesim Proseduru Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Orman_Kesim_Proseduru_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Personel_ISG_Ihtar_Detayli_Sablon', title: 'Personel ISG Ihtar Detayli Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Personel_ISG_Ihtar_Detayli_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'personelAdi','label':'Personel Adý','type':'text'},{'key':'ihtarNedeni','label':'Ýhtar Nedeni','type':'textarea'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'Pestisit_Talimati_Sablon', title: 'Pestisit Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Pestisit_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'PKD_Sablon', title: 'PKD Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/PKD_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'dokumanNo','label':'Doküman No','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] },
{ id: 'SERTÝFÝKA', title: 'SERTÝFÝKA', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/SERTÝFÝKA.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Sicak_Metal_Transfer_Talimati_Sablon', title: 'Sicak Metal Transfer Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Sicak_Metal_Transfer_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Soguk_Oda_Talimati_Sablon', title: 'Soguk Oda Talimati Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Soguk_Oda_Talimati_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'tarih','label':'Tarih','type':'date'},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'onaylayan','label':'Onaylayan','type':'text'}] },
{ id: 'Yangindan_Korunma_Dokumani_Sablon', title: 'Yangindan Korunma Dokumani Sablon', description: 'Doküman þablonu', category: 'Dökümanlar', isPremium: false, fileUrl: '/templates/Yangindan_Korunma_Dokumani_Sablon.doc', fields: [{'key':'firmaAdi','label':'Firma Adý','type':'text','required':true},{'key':'hazirlayan','label':'Hazýrlayan','type':'text'},{'key':'binaSorumlusu','label':'Bina Sorumlusu','type':'text'},{'key':'tarih','label':'Tarih','type':'date'}] }
];
